In [1]:
import rioxarray as rxr
import os
from rasterio.plot import show
from PIL import Image
import matplotlib.pyplot as plt
import xarray as xr
import rasterio
import numpy as np
import geopandas as gpd
import rasterio as rio

In [2]:
class_ID = "data/transfer_5941271_files_87719365/class_ID_2020.tif"
segment_ID = "data/transfer_5941271_files_87719365/segment_ID_2020.tif"
polygon_ID = "data/transfer_5941271_files_87719365/polygon_ID.tif"
new_data = "data/transfer_5943292_files_445176e1/s2_2020_B02.tif"

In [3]:
def open_tif(file, infos=False):
    with xr.open_rasterio(file) as ds:
        if infos:
            print(ds)
            print(ds.rio.crs)
            print(ds.rio.bounds())
            print(ds.rio.resolution())
            print(ds.rio.shape)
            print(ds.rio.transform())
            print(ds.rio.count)
    o_file = rxr.open_rasterio(file)
    return o_file

def show_file(o_file):
    display(o_file)
    show(o_file.data)
    return

In [ ]:
class_ID_array = open_tif(class_ID)
segment_ID_array = open_tif(segment_ID)
polygon_ID_array = open_tif(polygon_ID)

In [ ]:
# print a small part of the array
print(class_ID_array.shape)
print(polygon_ID_array.shape)
print(segment_ID_array.shape)

class_ID_array_full = class_ID_array.data[0]
polygon_ID_array_full = polygon_ID_array.data[0]
segment_ID_array_full = segment_ID_array.data[0]

print(class_ID_array_full.shape)
print(polygon_ID_array_full.shape)
print(segment_ID_array_full.shape)

(1, 4513, 5183)
(1, 4513, 5183)
(1, 4513, 5183)
(4513, 5183)
(4513, 5183)
(4513, 5183)


In [ ]:
# create test arrays
test_class_ID_array = np.random.randint(0, 8, (10, 10))
# polygons should be a matrix with groups of pixels with the same ID other is Nan
Nan = np.nan
test_polygon_ID_array = [[0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan]]
test_polygon_ID_array = np.array(test_polygon_ID_array)

test_segment_ID_array = [[14, 14, 7, 7, Nan, Nan, Nan, 2, 2, Nan],
                   [9, 8, 8, 8, Nan, Nan, Nan, Nan, Nan, 3],
                   [9, 1, 1, Nan, Nan, Nan, Nan, Nan, Nan, 3],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, 10, Nan, 4, 4, 4, 11, Nan, Nan, Nan],
                   [Nan, 10, Nan, 4, Nan, 5, 5, Nan, Nan, Nan],
                   [Nan, Nan, Nan, 6, 6, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan]]
test_segment_ID_array = np.array(test_segment_ID_array)

# fill segment_ID nan values with 0
test_segment_ID_array = np.nan_to_num(test_segment_ID_array, nan=0)

print(test_class_ID_array)
print(test_polygon_ID_array)
print(test_segment_ID_array)
# show shape
print(test_class_ID_array.shape)
print(test_polygon_ID_array.shape)
print(test_segment_ID_array.shape)


[[6 2 6 2 0 2 6 7 4 7]
 [0 5 5 7 5 0 3 3 5 0]
 [0 7 4 2 1 3 4 5 1 4]
 [1 6 3 3 2 7 2 7 7 6]
 [7 7 6 6 7 7 2 7 7 5]
 [6 1 1 3 0 0 4 4 0 1]
 [5 3 5 6 4 2 7 5 0 3]
 [4 0 7 4 5 3 3 7 7 4]
 [6 1 5 3 7 1 1 2 3 6]
 [6 3 5 6 3 2 3 1 3 1]]
[[ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
[[14. 14.  7.  7.  0.  0.  0.  2.  2.  0.]
 [ 9.  8.  8.  8.  0.  0.  0.  0.  0.  3.]
 [ 9.  1.  1.  0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  4.  4.  4. 11.  0.  0.  0.]
 [ 0. 10.  0.  4.  0.  5.  5.  0.  0.  0.]
 [ 0.  0.  0.  6.  6. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 12.  0.  0.  0.

In [ ]:
def find_fully_contained_segments(class_ID,segment_ID,polygon_ID,output_file):    
    # retreive all polygons
    polygons = np.unique(polygon_ID)
    polygons = polygons[~np.isnan(polygons)]
    iterations = len(polygons)
    
    # iterate through polygons
    for i in range(len(polygons)):
        print(f"Iteration {i+1}/{iterations}")
        # retreive pixels of polygon
        polygon = polygons[i]
        polygon_pixels = np.where(polygon_ID == polygon)
        polygon_pixels = np.array(polygon_pixels).T

        # retreive all segments of polygon
        polygon_segments = []
        for pixel in polygon_pixels:
            polygon_segments.append(segment_ID[pixel[0], pixel[1]])
        polygon_segments = np.unique(polygon_segments)
        
        # for each segments, get the lenght of pixels for both in polygon and in total
        for segment in polygon_segments:
            # retreive pixels of segment within polygon
            number_pixel_in = np.sum((segment_ID == segment) & (polygon_ID == polygon))
            number_pixel_total = np.sum(segment_ID == segment)

            segment_pixel_polygon = np.where((segment_ID == segment) & (polygon_ID == polygon))
            segment_pixel_polygon = np.array(segment_pixel_polygon).T
            
            # if lenght are equal then segment is totally included in polygon
            if (number_pixel_in) == (number_pixel_total):
                print(f"Segment {segment} is totally included in polygon {polygon}")
                # retreive the class of the segment
                class_id = class_ID[segment_pixel_polygon[0,0], segment_pixel_polygon[0,1]]

                # write in file
                print(f"Segment ID: {segment}, Polygon ID: {polygon}, Class ID: {class_id}, Pixels: {segment_pixel_polygon}\n")
                output_file.write(f"Segment ID: {segment}, Polygon ID: {polygon}, Class ID: {class_id}, Pixels: {segment_pixel_polygon}\n")
                


In [ ]:
def find_contained_segments(class_ID, segment_ID, polygon_ID, output_file, included_pixel_percentage=100):
    # Retrieve all polygons
    polygons = np.unique(polygon_ID)
    polygons = polygons[~np.isnan(polygons)]
    iterations = len(polygons)

    # Iterate through polygons
    for i in range(len(polygons)):
        print(f"Iteration {i + 1}/{iterations}")
        # Retrieve pixels of polygon
        polygon = polygons[i]
        polygon_pixels = np.where(polygon_ID == polygon)
        polygon_pixels = np.array(polygon_pixels).T

        # Retrieve all segments of polygon
        polygon_segments = []
        for pixel in polygon_pixels:
            polygon_segments.append(segment_ID[pixel[0], pixel[1]])
        polygon_segments = np.unique(polygon_segments)

        # For each segment, calculate the percentage of included pixels within the polygon
        for segment in polygon_segments:
            segment_pixels = np.where(segment_ID == segment)
            segment_pixels = np.array(segment_pixels).T
            total_pixels = len(segment_pixels)
            
            segment_pixel_polygon = np.where((segment_ID == segment) & (polygon_ID == polygon))
            segment_pixel_polygon = np.array(segment_pixel_polygon).T
            included_pixels = len(segment_pixel_polygon)

            # Calculate the percentage of included pixels
            percentage_included = (included_pixels / total_pixels) * 100

            if percentage_included >= included_pixel_percentage:
                # Retrieve the class of the segment
                class_id = class_ID[segment_pixel_polygon[0, 0], segment_pixel_polygon[0, 1]]

                # Generate the formatted pixel coordinates as lists
                pixel_coords = [list(pixel) for pixel in segment_pixels]

                # Write to the file in the desired format
                output_file.write(f"Segment ID: {segment}, Polygon ID: {polygon}, Class ID: {class_id}, Pixels: {pixel_coords}\n")


In [ ]:
print(test_class_ID_array.shape)
print(class_ID_array_full.shape)
print(test_polygon_ID_array.shape)
print(polygon_ID_array_full.shape)
print(test_segment_ID_array.shape)
print(segment_ID_array_full.shape)

print(test_class_ID_array[0,0])
print(class_ID_array_full[0,0])


# reduce the size of the arrays
start_x = 0
end_x = 2000
start_y = 0
end_y = 2000
class_ID_array_reduced = class_ID_array_full[:end_x, :end_y]
polygon_ID_array_reduced = polygon_ID_array_full[:end_x, :end_y]
segment_ID_array_reduced = segment_ID_array_full[:end_x, :end_y]

print(class_ID_array_reduced.shape)
print(polygon_ID_array_reduced.shape)
print(segment_ID_array_reduced.shape)

(10, 10)
(4513, 5183)
(10, 10)
(4513, 5183)
(10, 10)
(4513, 5183)
6
nan
(2000, 2000)
(2000, 2000)
(2000, 2000)


In [ ]:
print(test_class_ID_array)
print(test_polygon_ID_array)

[[6 2 6 2 0 2 6 7 4 7]
 [0 5 5 7 5 0 3 3 5 0]
 [0 7 4 2 1 3 4 5 1 4]
 [1 6 3 3 2 7 2 7 7 6]
 [7 7 6 6 7 7 2 7 7 5]
 [6 1 1 3 0 0 4 4 0 1]
 [5 3 5 6 4 2 7 5 0 3]
 [4 0 7 4 5 3 3 7 7 4]
 [6 1 5 3 7 1 1 2 3 6]
 [6 3 5 6 3 2 3 1 3 1]]
[[ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]


In [ ]:
print(test_segment_ID_array)

[[14. 14.  7.  7.  0.  0.  0.  2.  2.  0.]
 [ 9.  8.  8.  8.  0.  0.  0.  0.  0.  3.]
 [ 9.  1.  1.  0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  4.  4.  4. 11.  0.  0.  0.]
 [ 0. 10.  0.  4.  0.  5.  5.  0.  0.  0.]
 [ 0.  0.  0.  6.  6. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [13]:
# Example usage
output_file_name = "data/transfer_5943292_files_445176e1/contained_segments.txt"
with open(output_file_name, 'w') as output_file:
    find_contained_segments(class_ID_array_full, segment_ID_array_full, polygon_ID_array_full, output_file, included_pixel_percentage=50)
    #find_fully_contained_segments(class_ID_array_reduced, segment_ID_array_reduced, polygon_ID_array_reduced, output_file)
    #find_fully_contained_segments(test_class_ID_array, test_segment_ID_array, test_polygon_ID_array, output_file)

Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fu

In [ ]:
# lets manipulate the file
# start by counting how many contained segments there are
