In [1]:
import rioxarray as rxr
import os
from rasterio.plot import show
from PIL import Image
import matplotlib.pyplot as plt
import xarray as xr
import rasterio
import numpy as np
import geopandas as gpd
import rasterio as rio

In [2]:
class_ID = "data/transfer_5941271_files_87719365/class_ID_2020.tif"
segment_ID = "data/transfer_5941271_files_87719365/segment_ID_2020.tif"
polygon_ID = "data/transfer_5941271_files_87719365/polygon_ID.tif"
new_data = "data/transfer_5943292_files_445176e1/s2_2020_B02.tif"

In [3]:
def open_tif(file, infos=False):
    with xr.open_rasterio(file) as ds:
        if infos:
            print(ds)
            print(ds.rio.crs)
            print(ds.rio.bounds())
            print(ds.rio.resolution())
            print(ds.rio.shape)
            print(ds.rio.transform())
            print(ds.rio.count)
    o_file = rxr.open_rasterio(file)
    return o_file

def show_file(o_file):
    display(o_file)
    show(o_file.data)
    return

In [4]:
class_ID_array = open_tif(class_ID)
segment_ID_array = open_tif(segment_ID)
polygon_ID_array = open_tif(polygon_ID)

C:\Users\antoi\AppData\Local\Temp\ipykernel_19628\3002180342.py:2: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  with xr.open_rasterio(file) as ds:


C:\Users\antoi\AppData\Local\Temp\ipykernel_19628\3002180342.py:2: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  with xr.open_rasterio(file) as ds:
C:\Users\antoi\AppData\Local\Temp\ipykernel_19628\3002180342.py:2: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  with xr.open_rasterio(file) as ds:


In [5]:
# print a small part of the array
print(class_ID_array.shape)
print(polygon_ID_array.shape)
print(segment_ID_array.shape)

class_ID_array_full = class_ID_array.data[0]
polygon_ID_array_full = polygon_ID_array.data[0]
segment_ID_array_full = segment_ID_array.data[0]

print(class_ID_array_full.shape)
print(polygon_ID_array_full.shape)
print(segment_ID_array_full.shape)

(1, 4513, 5183)
(1, 4513, 5183)
(1, 4513, 5183)
(4513, 5183)
(4513, 5183)
(4513, 5183)


In [6]:
# create test arrays
test_class_ID_array = np.random.randint(0, 8, (10, 10))
# polygons should be a matrix with groups of pixels with the same ID other is Nan
Nan = np.nan
test_polygon_ID_array = [[0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan]]
test_polygon_ID_array = np.array(test_polygon_ID_array)

test_segment_ID_array = [[14, 14, 7, 7, Nan, Nan, Nan, 2, 2, Nan],
                   [9, 8, 8, 8, Nan, Nan, Nan, Nan, Nan, 3],
                   [9, 1, 1, Nan, Nan, Nan, Nan, Nan, Nan, 3],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, 10, Nan, 4, 4, 4, 11, Nan, Nan, Nan],
                   [Nan, 10, Nan, 4, Nan, 5, 5, Nan, Nan, Nan],
                   [Nan, Nan, Nan, 6, 6, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan]]
test_segment_ID_array = np.array(test_segment_ID_array)

# fill segment_ID nan values with 0
test_segment_ID_array = np.nan_to_num(test_segment_ID_array, nan=0)

print(test_class_ID_array)
print(test_polygon_ID_array)
print(test_segment_ID_array)
# show shape
print(test_class_ID_array.shape)
print(test_polygon_ID_array.shape)
print(test_segment_ID_array.shape)


[[6 2 6 2 0 2 6 7 4 7]
 [0 5 5 7 5 0 3 3 5 0]
 [0 7 4 2 1 3 4 5 1 4]
 [1 6 3 3 2 7 2 7 7 6]
 [7 7 6 6 7 7 2 7 7 5]
 [6 1 1 3 0 0 4 4 0 1]
 [5 3 5 6 4 2 7 5 0 3]
 [4 0 7 4 5 3 3 7 7 4]
 [6 1 5 3 7 1 1 2 3 6]
 [6 3 5 6 3 2 3 1 3 1]]
[[ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
[[14. 14.  7.  7.  0.  0.  0.  2.  2.  0.]
 [ 9.  8.  8.  8.  0.  0.  0.  0.  0.  3.]
 [ 9.  1.  1.  0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  4.  4.  4. 11.  0.  0.  0.]
 [ 0. 10.  0.  4.  0.  5.  5.  0.  0.  0.]
 [ 0.  0.  0.  6.  6. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 12.  0.  0.  0.

In [7]:
def find_fully_contained_segments(class_ID,segment_ID,polygon_ID,output_file):    
    # retreive all polygons
    polygons = np.unique(polygon_ID)
    polygons = polygons[~np.isnan(polygons)]
    iterations = len(polygons)
    
    # iterate through polygons
    for i in range(len(polygons)):
        print(f"Iteration {i+1}/{iterations}")
        # retreive pixels of polygon
        polygon = polygons[i]
        polygon_pixels = np.where(polygon_ID == polygon)
        polygon_pixels = np.array(polygon_pixels).T

        # retreive all segments of polygon
        polygon_segments = []
        for pixel in polygon_pixels:
            polygon_segments.append(segment_ID[pixel[0], pixel[1]])
        polygon_segments = np.unique(polygon_segments)
        
        # for each segments, get the lenght of pixels for both in polygon and in total
        for segment in polygon_segments:
            # retreive pixels of segment within polygon
            number_pixel_in = np.sum((segment_ID == segment) & (polygon_ID == polygon))
            number_pixel_total = np.sum(segment_ID == segment)

            segment_pixel_polygon = np.where((segment_ID == segment) & (polygon_ID == polygon))
            segment_pixel_polygon = np.array(segment_pixel_polygon).T
            
            # if lenght are equal then segment is totally included in polygon
            if (number_pixel_in) == (number_pixel_total):
                print(f"Segment {segment} is totally included in polygon {polygon}")
                # retreive the class of the segment
                class_id = class_ID[segment_pixel_polygon[0,0], segment_pixel_polygon[0,1]]

                # write in file
                print(f"Segment ID: {segment}, Polygon ID: {polygon}, Class ID: {class_id}, Pixels: {segment_pixel_polygon}\n")
                output_file.write(f"Segment ID: {segment}, Polygon ID: {polygon}, Class ID: {class_id}, Pixels: {segment_pixel_polygon}\n")
                


In [8]:
import numpy as np

def find_fully_contained_segments(class_ID, segment_ID, polygon_ID, output_file):
    iteration = 0
    total_iterations = 998
    
    unique_polygons = np.unique(polygon_ID)

    for polygon in unique_polygons:
        print(f"Iteration in progress: {iteration}/{total_iterations}", end="\r")
        if not np.isnan(polygon):  # Skip processing 'nan'
            polygon_indices = np.where(polygon_ID == polygon)
            segment_counts = {}

            # Count the pixels for each segment within the polygon
            for i, j in zip(*polygon_indices):
                segment = segment_ID[i, j]
                if segment in segment_counts:
                    segment_counts[segment] += 1
                else:
                    segment_counts[segment] = 1

            # Check if a segment is fully contained in the polygon
            for segment, count in segment_counts.items():
                total_segment_pixels = np.sum(segment_ID == segment)
                if count == total_segment_pixels:
                    print("Found a fully contained segment!")
                    pixels = np.argwhere(segment_ID == segment).tolist()
                    
                    # Extract 'Class ID' from any pixel in the segment (e.g., using the first pixel)
                    class_id = class_ID[pixels[0][0], pixels[0][1]]
                    
                    # Write the fully contained segment to the output file
                    output_file.write(f"Segment ID: {segment}, Polygon ID: {polygon}, Class ID: {class_id}, Pixels: {pixels}\n")
                    
        iteration += 1

In [9]:
print(test_class_ID_array.shape)
print(class_ID_array_full.shape)
print(test_polygon_ID_array.shape)
print(polygon_ID_array_full.shape)
print(test_segment_ID_array.shape)
print(segment_ID_array_full.shape)

print(test_class_ID_array[0,0])
print(class_ID_array_full[0,0])


# reduce the size of the arrays
start_x = 0
end_x = 2000
start_y = 0
end_y = 2000
class_ID_array_reduced = class_ID_array_full[:end_x, :end_y]
polygon_ID_array_reduced = polygon_ID_array_full[:end_x, :end_y]
segment_ID_array_reduced = segment_ID_array_full[:end_x, :end_y]

print(class_ID_array_reduced.shape)
print(polygon_ID_array_reduced.shape)
print(segment_ID_array_reduced.shape)

(10, 10)
(4513, 5183)
(10, 10)
(4513, 5183)
(10, 10)
(4513, 5183)
6
nan
(2000, 2000)
(2000, 2000)
(2000, 2000)


In [10]:
print(test_class_ID_array)
print(test_polygon_ID_array)

[[6 2 6 2 0 2 6 7 4 7]
 [0 5 5 7 5 0 3 3 5 0]
 [0 7 4 2 1 3 4 5 1 4]
 [1 6 3 3 2 7 2 7 7 6]
 [7 7 6 6 7 7 2 7 7 5]
 [6 1 1 3 0 0 4 4 0 1]
 [5 3 5 6 4 2 7 5 0 3]
 [4 0 7 4 5 3 3 7 7 4]
 [6 1 5 3 7 1 1 2 3 6]
 [6 3 5 6 3 2 3 1 3 1]]
[[ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]


In [11]:
print(test_segment_ID_array)

[[14. 14.  7.  7.  0.  0.  0.  2.  2.  0.]
 [ 9.  8.  8.  8.  0.  0.  0.  0.  0.  3.]
 [ 9.  1.  1.  0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  4.  4.  4. 11.  0.  0.  0.]
 [ 0. 10.  0.  4.  0.  5.  5.  0.  0.  0.]
 [ 0.  0.  0.  6.  6. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [12]:
print(polygon_ID_array_full[1146, 2939])

4.0


In [ ]:
for i in range(0, 100):
    polygon_pixels = np.where(polygon_ID_array_full == i)
    polygon_pixels = np.array(polygon_pixels).T
    print(f"Pollygon number {i} has {len(polygon_pixels)} pixels")

In [23]:
polygon = 703

polygon_pixels = np.where(polygon_ID_array_full == polygon)
polygon_pixels = np.array(polygon_pixels).T
print(f"Polygon number {polygon} has {len(polygon_pixels)} pixels")

polygon_segments = []
for pixel in polygon_pixels:
    polygon_segments.append(segment_ID_array_full[pixel[0], pixel[1]])
polygon_segments = np.unique(polygon_segments)
print("Unique segments in polygon:")
print(len(polygon_segments))
print(polygon_segments)
count = 0
for segment in polygon_segments:
    number_pixel_in = np.sum((segment_ID_array_full == segment) & (polygon_ID_array_full == polygon))
    count += number_pixel_in
    number_pixel_total = np.sum(segment_ID_array_full == segment)
    print(f"Segment {segment} has {number_pixel_in} pixels in polygon and {number_pixel_total} pixels in total")
    
print(count)

Polygon number 703 has 267 pixels
Unique segments in polygon:
27
[114740 116006 116007 116008 116009 116010 116011 116956 116957 117307
 117308 117309 117310 117311 117312 118605 118606 118607 118608 118609
 118610 119867 119868 119869 119870 121171 121172]
Segment 114740 has 2 pixels in polygon and 16 pixels in total
Segment 116006 has 2 pixels in polygon and 19 pixels in total
Segment 116007 has 6 pixels in polygon and 15 pixels in total
Segment 116008 has 14 pixels in polygon and 16 pixels in total
Segment 116009 has 16 pixels in polygon and 16 pixels in total
Segment 116010 has 13 pixels in polygon and 16 pixels in total
Segment 116011 has 8 pixels in polygon and 16 pixels in total
Segment 116956 has 13 pixels in polygon and 16 pixels in total
Segment 116957 has 10 pixels in polygon and 20 pixels in total
Segment 117307 has 1 pixels in polygon and 13 pixels in total
Segment 117308 has 17 pixels in polygon and 17 pixels in total
Segment 117309 has 16 pixels in polygon and 16 pixels 

In [26]:
polygons = np.unique(polygon_ID_array_full)
polygons = polygons[~np.isnan(polygons)]
iterations = len(polygons)

# retreive pixels of polygon
polygon = polygons[0]
polygon_pixels = np.where(polygon_ID_array_full == polygon)
polygon_pixels = np.array(polygon_pixels).T

# retreive all segments of polygon
polygon_segments = np.unique(segment_ID_array_full[polygon_pixels])

# for each segments, get the lenght of pixels for both in polygon and in total
for segment in polygon_segments:
    # retreive pixels of segment within polygon
    segment_pixel_polygon = np.where((segment_ID_array_full == segment) & (polygon_ID_array_full == polygon))
    segment_pixel_polygon = np.array(segment_pixel_polygon).T
    segment_pixels_total = np.where(segment_ID_array_full == segment)
    segment_pixels_total = np.array(segment_pixels_total).T

    # if lenght are equal then segment is totally included in polygon
    if len(segment_pixel_polygon) == len(segment_pixels_total):
        print(f"Segment {segment} is totally included in polygon {polygon}")

KeyboardInterrupt: 

In [13]:
# Example usage
output_file_name = "data/transfer_5943292_files_445176e1/fully_contained_segments.txt"
with open(output_file_name, 'w') as output_file:
    find_fully_contained_segments(class_ID_array_full, segment_ID_array_full, polygon_ID_array_full, output_file)
    #find_fully_contained_segments(class_ID_array_reduced, segment_ID_array_reduced, polygon_ID_array_reduced, output_file)
    #find_fully_contained_segments(test_class_ID_array, test_segment_ID_array, test_polygon_ID_array, output_file)

Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fully contained segment!
Found a fu

In [ ]:
# lets manipulate the file
# start by counting how many contained segments there are
