In [2]:
import rioxarray as rxr
import os
from rasterio.plot import show
from PIL import Image
import matplotlib.pyplot as plt
import xarray as xr
import rasterio
import numpy as np
import geopandas as gpd
import rasterio as rio

In [38]:
class_ID = "data/transfer_5941271_files_87719365/class_ID_2020.tif"
segment_ID = "data/transfer_5941271_files_87719365/segment_ID_2020.tif"
polygon_ID = "data/transfer_5941271_files_87719365/polygon_ID.tif"
new_data = "data/transfer_5943292_files_445176e1/s2_2020_B02.tif"

In [39]:
def open_tif(file, infos=False):
    with xr.open_rasterio(file) as ds:
        if infos:
            print(ds)
            print(ds.rio.crs)
            print(ds.rio.bounds())
            print(ds.rio.resolution())
            print(ds.rio.shape)
            print(ds.rio.transform())
            print(ds.rio.count)
    o_file = rxr.open_rasterio(file)
    return o_file

def show_file(o_file):
    display(o_file)
    show(o_file.data)
    return

In [40]:
class_ID_array = open_tif(class_ID)
segment_ID_array = open_tif(segment_ID)
polygon_ID_array = open_tif(polygon_ID)

C:\Users\antoi\AppData\Local\Temp\ipykernel_18868\3002180342.py:2: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  with xr.open_rasterio(file) as ds:
C:\Users\antoi\AppData\Local\Temp\ipykernel_18868\3002180342.py:2: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  with xr.open_rasterio(file) as ds:
C:\Users\antoi\AppData\Local\Temp\ipykernel_18868\3002180342.py:2: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  with xr.open_rasterio(file) as ds:


In [41]:
# print a small part of the array
print(class_ID_array.shape)
print(polygon_ID_array.shape)
print(segment_ID_array.shape)

class_ID_array_full = class_ID_array.data[0]
polygon_ID_array_full = polygon_ID_array.data[0]
segment_ID_array_full = segment_ID_array.data[0]

print(class_ID_array_full.shape)
print(polygon_ID_array_full.shape)
print(segment_ID_array_full.shape)

(1, 4513, 5183)
(1, 4513, 5183)
(1, 4513, 5183)
(4513, 5183)
(4513, 5183)
(4513, 5183)


In [29]:
# create test arrays
test_class_ID_array = np.random.randint(0, 8, (10, 10))
# polygons should be a matrix with groups of pixels with the same ID other is Nan
Nan = np.nan
test_polygon_ID_array = [[0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [0, 0, 0, Nan, Nan, Nan, Nan, 1, 1, 1],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, 2, 2, 2, 2, 2, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan]]
test_polygon_ID_array = np.array(test_polygon_ID_array)

test_segment_ID_array = [[0, 0, 7, 7, Nan, Nan, Nan, 2, 2, Nan],
                   [9, 8, 8, 8, Nan, Nan, Nan, Nan, Nan, 3],
                   [9, 1, 1, Nan, Nan, Nan, Nan, Nan, Nan, 3],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan],
                   [Nan, 10, Nan, 4, 4, 4, 11, Nan, Nan, Nan],
                   [Nan, 10, Nan, 4, Nan, 5, 5, Nan, Nan, Nan],
                   [Nan, Nan, Nan, 6, 6, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, 12, Nan, Nan, Nan, Nan],
                   [Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan, Nan]]
test_segment_ID_array = np.array(test_segment_ID_array)

print(test_class_ID_array)
print(test_polygon_ID_array)
print(test_segment_ID_array)
# show shape
print(test_class_ID_array.shape)
print(test_polygon_ID_array.shape)
print(test_segment_ID_array.shape)

[[7 0 0 0 4 7 5 5 4 1]
 [3 0 7 7 0 4 1 1 7 3]
 [7 4 0 7 0 0 4 7 2 5]
 [4 7 2 5 2 3 0 7 6 4]
 [1 2 6 7 0 5 2 3 6 0]
 [1 0 6 3 7 6 3 5 5 4]
 [2 1 4 5 6 0 6 1 2 4]
 [5 4 1 6 1 5 6 0 6 0]
 [7 0 3 3 6 2 7 4 7 6]
 [7 1 5 1 7 2 1 7 5 7]]
[[ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [ 0.  0.  0. nan nan nan nan  1.  1.  1.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan  2.  2.  2.  2.  2. nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
[[ 0.  0.  7.  7. nan nan nan  2.  2. nan]
 [ 9.  8.  8.  8. nan nan nan nan nan  3.]
 [ 9.  1.  1. nan nan nan nan nan nan  3.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan 10. nan  4.  4.  4. 11. nan nan nan]
 [nan 10. nan  4. nan  5.  5. nan nan nan]
 [nan nan nan  6.  6. 12. nan nan nan nan]
 [nan nan nan nan nan 12. nan nan nan

In [35]:
import numpy as np

def find_fully_contained_segments(segment_ID_array, polygon_ID_array):
    # Convert the input arrays to NumPy arrays
    segment_ID_array = np.array(segment_ID_array)
    polygon_ID_array = np.array(polygon_ID_array)

    # Get the unique segment IDs and unique polygon IDs
    unique_segment_ids = np.unique(segment_ID_array)
    unique_polygon_ids = np.unique(polygon_ID_array)

    # Create a mask for valid segments (non-NaN)
    valid_segments = ~np.isnan(unique_segment_ids)

    # Initialize a dictionary to store fully contained segments
    fully_contained_segments = {}

    # Iterate through each valid segment
    for segment_ID in unique_segment_ids[valid_segments]:
        # Create a mask for pixels where the segment ID matches
        segment_mask = (segment_ID_array == segment_ID)

        # Check if the segment is fully contained within any polygon
        fully_contained = np.all(polygon_ID_array[segment_mask] == polygon_ID_array[segment_mask][0])

        if fully_contained:
            # Store the segment ID and its corresponding polygon ID
            polygon_ID = polygon_ID_array[segment_mask][0]

            if polygon_ID not in fully_contained_segments:
                fully_contained_segments[polygon_ID] = []

            fully_contained_segments[polygon_ID].append([segment_ID, np.argwhere(segment_mask).tolist()])

    return fully_contained_segments

# Use the function to find fully contained segments
fully_contained_segments = find_fully_contained_segments(test_segment_ID_array, test_polygon_ID_array)

# Print the fully contained segments
for polygon_ID, segments in fully_contained_segments.items():
    for segment in segments:
        print(f"Segment ID: {segment[0]}, Polygon ID: {polygon_ID}, Pixels: {segment[1]}")
        


Segment ID: 0.0, Polygon ID: 0.0, Pixels: [[0, 0], [0, 1]]
Segment ID: 1.0, Polygon ID: 0.0, Pixels: [[2, 1], [2, 2]]
Segment ID: 9.0, Polygon ID: 0.0, Pixels: [[1, 0], [2, 0]]
Segment ID: 2.0, Polygon ID: 1.0, Pixels: [[0, 7], [0, 8]]
Segment ID: 3.0, Polygon ID: 1.0, Pixels: [[1, 9], [2, 9]]
Segment ID: 4.0, Polygon ID: 2.0, Pixels: [[4, 3], [4, 4], [4, 5], [5, 3]]
Segment ID: 5.0, Polygon ID: 2.0, Pixels: [[5, 5], [5, 6]]
Segment ID: 6.0, Polygon ID: 2.0, Pixels: [[6, 3], [6, 4]]
Segment ID: 11.0, Polygon ID: 2.0, Pixels: [[4, 6]]


In [34]:
# put fully contained segments into a file
file_name = "data/transfer_5943292_files_445176e1/fully_contained_segments.txt"
with open(file_name, 'w') as f:
    for polygon_ID, segments in fully_contained_segments.items():
        for segment in segments:
            f.write(f"Segment ID: {segment[0]}, Polygon ID: {polygon_ID}, Pixels: {segment[1]}\n")

In [ ]:
print()